version: '2.2'
services:
  mysql:
    container_name: mysql-springboot-sample
    image: mysql:8
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    environment:
      MYSQL_DATABASE: springboot_sample
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3307:3306
